# Generated by Django 5.2.6 on 2025-10-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='description',
        ),
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Flower', 'Flower'), ('Herb', 'Herb'), ('Tree', 'Tree'), ('Indoor', 'Indoor')], default='Vegetable', max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plants/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
