# Generated by Django 5.2.6 on 2025-11-13 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Watered', 'Watered'), ('Fertilized', 'Fertilized'), ('Sunlight', 'Sunlight'), ('Pruned', 'Pruned'), ('Repotted', 'Repotted'), ('Other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='core.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
