# Generated by Django 5.2.6 on 2025-11-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_plant_sunlight_interval_plant_watering_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sunlight_interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_interval',
            field=models.IntegerField(default=3),
        ),
    ]
