# Generated by Django 5.2.6 on 2025-11-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_plant_sunlight_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_sunlight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
