# Generated by Django 5.2.6 on 2025-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plant_last_sunlight_plant_last_watered'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
