# Generated by Django 5.2.6 on 2025-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('expert', 'Expert'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
