# Generated by Django 6.0.2 on 2026-02-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_diseaseprofile_prediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='dynamic_watering_interval',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_weather_adjusted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='location_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='weather_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_key', models.CharField(db_index=True, max_length=160)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('next24h_rain_prob_max', models.FloatField(default=0.0)),
                ('next24h_rain_mm_sum', models.FloatField(default=0.0)),
                ('next48h_temp_max', models.FloatField(default=0.0)),
                ('next48h_temp_min', models.FloatField(default=0.0)),
                ('frost_risk', models.BooleanField(default=False)),
                ('heatwave_risk', models.BooleanField(default=False)),
                ('provider', models.CharField(default='open-meteo', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('forecast_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_at'],
                'indexes': [models.Index(fields=['location_key', '-forecast_at'], name='core_weathe_locatio_269144_idx')],
            },
        ),
        migrations.CreateModel(
            name='SmartReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('watering_skipped_rain', 'watering_skipped_rain'), ('heatwave_alert', 'heatwave_alert'), ('frost_warning', 'frost_warning'), ('interval_adjusted', 'interval_adjusted')], max_length=64)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=16)),
                ('decision_reason', models.TextField(blank=True, default='')),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_events', to='core.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plant', '-created_at'], name='core_smartr_plant_i_ac7937_idx'), models.Index(fields=['user', 'is_sent'], name='core_smartr_user_id_2cc99a_idx')],
            },
        ),
    ]
