# Generated by Django 6.0.2 on 2026-02-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_plant_dynamic_watering_interval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('window_days', models.IntegerField(default=30)),
                ('watering_subscore', models.FloatField(default=0.0)),
                ('fertilizing_subscore', models.FloatField(default=0.0)),
                ('disease_subscore', models.FloatField(default=0.0)),
                ('growth_subscore', models.FloatField(default=0.0)),
                ('missed_subscore', models.FloatField(default=0.0)),
                ('version', models.CharField(default='health_v1', max_length=32)),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='core.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_health_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plant', '-created_at'], name='core_planth_plant_i_8f1962_idx'), models.Index(fields=['user', '-created_at'], name='core_planth_user_id_a17a3a_idx')],
            },
        ),
    ]
